### ISSUE TITLE
crash on server or client when placing any asset from the original level.

### ISSUE THREAD

**Issue by keku645** [SassythSasqutch/vu-spterrains#1]
Server crashes when placing any asset from the original level you're on, in the other hand any other asset which is imported from external levels (bundles) dont crash.

exact crash on:

---------------------------
mapeditor-test
---------------------------
[string "Modules/GameObjectManager.lua"]:513: OnEntityCreate

**Comment by SassythSasqutch** [comment]
Seemingly only for SP levels. COOP levels allow you to place assets from the level itself.

**Comment by SassythSasqutch** [comment]
Resolved in recent commit.
